### PR TITLE
breaking: make it compatible with memo and react compiler

### PR DESCRIPTION
**Pull request by dai-shi**
- [x] impl
- [x] docs

### CODE REVIEW

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/react-tracked/v/2.0.0-beta.2

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/react-tracked/v/2.0.0-beta.3

**Comment by grumd** [comment]
I just tried beta.3 in our repo from work. Admittedly we haven't used "memo" from react-tracked, only "createContainer" to avoid extra rerenders.

Everything works just like before, avoiding any extra rerenders. I haven't found any issues with 2.0.

Not sure how common my use-case is but we do something like this, putting the update function into the state object itself:

```js
const useFormStateValue = ({ state }) => {
  return [state, _.noop];
};

const { Provider, useTrackedState } = createContainer(useFormStateValue);

const Form = ({ values, setValues }) => {
  return (
    <Provider state={{ values, setValues }}>
      {...}
    </Provider>
  );
} 
```

Form components like radiobuttons and text boxes then use `useTrackedState` and get their value via `values.foo`. With react-tracked only the edited fields rerender and the rest of the form doesn't. Some of the fields can even have weird accessors like `_.get(values, 'foo[0].bar')` and it still works.

**Comment by dai-shi** [comment]
Thanks for confirming. Yes, the core change in this PR is subtle, and unless people use `memo` from RT (which is fairly rare, I guess), it should be fine.

**Pull request merged**
