### PR TITLE
export defaultContext and customContext

### PR DESCRIPTION
**Pull request by kevinya**
I would like to get access to those context for a custom hook using react-tracked.

### CODE REVIEW

**Comment by dai-shi** [comment]
May I ask your use case? I would like to learn it. 

I have thought about this. But, currently I would hide the context as an implementation detail, because I have a possible plan to have dual contexts eventually if that makes more sense.

**Comment by kevinya** [comment]
I planned to publish a state management library based on react-tracked and this [example](https://codesandbox.io/s/late-tdd-hlckt). I would be able to access actions from a global import.
```
import { useActions } from 'library';
const actions = useActions(); // that uses defaultContext
const actions = useActions(customContext); // if I want a particular context
```
But I just saw that `createProvider` is hardcoded with `state` and `dispatch` in value.



So I will just create a hook that `useDispatch` like [that](https://codesandbox.io/s/eager-hooks-4kihg) .

**Comment by dai-shi** [comment]
Thanks for the explanation. That’s the use case I’d like to support. 

Please see examples/06_customhook, which should be another solution. It’s using useTracked but it can be useActions = useDispatch. 

The problem is the naming of hooks. I’d like to solve this without exporting contexts. Any thoughts?

**Comment by dai-shi** [comment]
Please check out #16 and let me know if it solved your use cases. Thanks!

**Pull request closed without merging**
