### PR TITLE
chore(.github/workflows): change 'npm' to 'pnpm'

### PR DESCRIPTION
**Pull request by sukvvon**
* We are using `pnpm`, so i change it `npm` to `pnpm`

### CODE REVIEW

**Comment by dai-shi** [comment]
It's not a big deal, right? Let me know your thoughts

If this is critical, I can batch update all of my repos with automated scripts.

**Comment by sukvvon** [comment]
> It's not a big deal, right? Let me know your thoughts

I just wanted to make an update. There’s no particular intention behind it. Normally, I prefer to create PRs in smaller chunks. But if you prefer, I can batch them into a single one.

> If this is critical, I can batch update all of my repos with automated scripts.

It's not critical, Do you have automated scripts?

**Comment by sukvvon** [comment]
@dai-shi 

> If this is only the reason, I'll do an automated (bash) script. I have more than 30 repos with this config.

May I ask what kind of content is included in the automated (bash) script? I’m simply curious!

**Comment by dai-shi** [comment]
It's one liner:
```bash
for i in *; do [ -d $i ] && (cd $i; if [ `git branch --show-current` = "main" ] && [ -e .github/workflows/ci.yml ] && git pull && cmp -s ../ci.yml.old .github/workflows/ci.yml; then \cp ../ci.yml.new .github/workflows/ci.yml; git commit -am 'bulk update github workflows'; git push; fi); done
```

**Pull request closed without merging**
