### PR TITLE
fix: support memo with forwarded ref

### LINKED ISSUE #78: Memo doesn't work with forwarded ref
Hello and thank you for all this work! 🤗

When using the memo function (from `react-tracked`) with a component using `React.forwardRef`, I encounter several errors:

```
Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

By changing the code in this way, everything works again ⬇️ 

```ts
export function memo(
  Component: any,
  propsAreEqual?: any,
) {
  const WrappedComponent = forwardRef((props: any, ref: any) => {
    Object.values(props).forEach(trackMemo);
    return createElement(Component, { ...props, ref );
  });
  return reactMemo(WrappedComponent, propsAreEqual);
}
```

Have you ever encountered this kind of error? I can open a PR if you want!

Greetings from Paris 🇫🇷.

### PR DESCRIPTION
**Pull request by LeoLeBras**
Fix #78 

Note: I am more used to ReasonML/Rescript than Typescript, I hope everything is ok. 🙌

### CODE REVIEW

**Comment by dai-shi** [comment]
Hey thanks!
You modified 09_reactmemo example, but that example works without the modification, right?
I'd like to keep it unchanged for reference.
Can you please either make a new example, or create a new component in 09_reactmemo?
Or `__tests__/02_memo_spec.tsx` is fine too.

**Review by LeoLeBras — COMMENTED** [review]
I've just added a new example 🤗

**Review by dai-shi — APPROVED** [review]
Looks good. Thanks so much!

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/react-tracked/v/1.6.3

**Pull request merged**
