### PR TITLE
fix: read-only and non-configurable data property error

### LINKED ISSUE #79: ToDo App (useState+Immer) Error: 'get' on proxy: property '0' is a read-only and non-configurable data property
Hello and thank you for this amazing work!

I'm trying to understand and use this amazing lib, one thing that I did was clone the sandbox example of ToDo App (useState+Immer) and update the version of immer to 8.0.0 but I just got this error:

image

Do you know how I can fix it?

Thank you in advance!

### PR DESCRIPTION
**Pull request by dai-shi**
close #79

### CODE REVIEW

**Comment by dai-shi** [comment]
Hmmm, unfortunately it doesn't fix the original issue.
https://codesandbox.io/s/jolly-lamport-v7def?file=/package.json

**Comment by dai-shi** [comment]
Now, it's fixed.
https://codesandbox.io/s/elated-bohr-2q3sl

@chicus12 @wisammechano Would you guys like to confirm?

**Comment by dai-shi** [comment]
Pretty sure it's good to go.

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/react-tracked/v/1.6.4

**Comment by chicus12** [comment]
Hi @dai-shi, I confirm that the issue was fixed, thanks for your work.

**Comment by wisammechano** [comment]
Thanks @dai-shi , the issue is fixed

**Pull request merged**
